apiVersion: v1
kind: Service
metadata:
  labels:
    app: sports-platform
  name: sports-platform
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sports-platform
  type: NodePort
